### ISSUE TITLE
[1.20.1] Problems figuring out config.

### ISSUE THREAD

**Issue by 4AC11** [cubicoder/Well-Mod#2]
I'm trying to make the wells produce water in the overworld, lava in the nether, and the ooze fluid from enlightened end in the end.
my current list config looks like this:
`dataList = ["{MinTicks:50,MaxTicks:60,Fluid:{FluidName:"minecraft:lava",Amount:1000},BiomeTags:["nether"]}", "{MinTicks:50,MaxTicks:60,Fluid:{FluidName:"enlightened_end:ooze_fluid",Amount:1000},BiomeTags:["end"]}"]`
but when I try to join my game freezes up and crashes, and i get this in my latest.log:
`[23:56:52] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file well-server.toml of type SERVER for modid well
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:47) ~[fmlcore-1.20.1-47.2.20.jar%23687!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:60) ~[fmlcore-1.20.1-47.2.20.jar%23687!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.20.1-47.2.20.jar%23687!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.20.1-47.2.20.jar%23687!/:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:96) ~[forge-1.20.1-47.2.20-universal.jar%23691!/:?]
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23686!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23686!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23686!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid separator 'm' in array.
	at com.electronwill.nightconfig.toml.ArrayParser.parse(ArrayParser.java:39) ~[toml-3.6.4.jar%2394!/:?]
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:33) ~[toml-3.6.4.jar%2394!/:?]
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:69) ~[toml-3.6.4.jar%2394!/:?]
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:57) ~[toml-3.6.4.jar%2394!/:?]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.4.jar%2394!/:?]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.4.jar%2394!/:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.4.jar%2393!/:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.4.jar%2393!/:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.4.jar%2393!/:?]
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.4.jar%2393!/:?]
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.4.jar%2393!/:?]
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:43) ~[fmlcore-1.20.1-47.2.20.jar%23687!/:?]
	... 10 more`
I have no clue what to make of this other than I did something wrong with the formatting, I would appreciate any help or better examples on how to actually make the config work.

**Comment by cubicoder** [comment]
In 1.20.1, the format for biome tags is a little different than what you have. Instead of `BiomeTags:["nether"]`, you'll need `BiomeTags:["minecraft:is_nether"]`, and likewise instead of `BiomeTags:["end"]` you need `BiomeTags:["minecraft:is_end"]`. Check out [the wiki](https://github.com/cubicoder/Well-Mod/wiki) to see more about the config.

**Comment by 4AC11** [comment]
> In 1.20.1, the format for biome tags is a little different than what you have. Instead of `BiomeTags:["nether"]`, you'll need `BiomeTags:["minecraft:is_nether"]`, and likewise instead of `BiomeTags:["end"]` you need `BiomeTags:["minecraft:is_end"]`. Check out [the wiki](https://github.com/cubicoder/Well-Mod/wiki) to see more about the config.

Thanks for responding. I changed the biome tags like you said but nothing changed, I'm still getting the same crash.

**Comment by cubicoder** [comment]
I loaded up a test world with Enlightened End and everything worked fine for me. Can you send your mod list, your latest.log, and your config file?

**Comment by 4AC11** [comment]
Hi, sorry, I didn't see this reply.
Here's my config file:
`dataList = ["{MinTicks:50,MaxTicks:60,Fluid:{FluidName:"minecraft:lava",Amount:1000},BiomeTags:["minecraft:is_nether"]}", "{MinTicks:50,MaxTicks:60,Fluid:{FluidName:"enlightened_end:ooze_fluid",Amount:1000},BiomeTags:["minecraft:is_end"]}"]`
(the first lines are unchanged)
And the tail end of my latest.log: 
`[14:58:08] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file well-server.toml of type SERVER for modid well
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:47) ~[fmlcore-1.20.1-47.2.20.jar%23711!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:60) ~[fmlcore-1.20.1-47.2.20.jar%23711!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.20.1-47.2.20.jar%23711!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.20.1-47.2.20.jar%23711!/:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:96) ~[forge-1.20.1-47.2.20-universal.jar%23715!/:?]
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23710!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23710!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23710!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid separator 'm' in array.
	at com.electronwill.nightconfig.toml.ArrayParser.parse(ArrayParser.java:39) ~[toml-3.6.4.jar%2394!/:?]
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:33) ~[toml-3.6.4.jar%2394!/:?]
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:69) ~[toml-3.6.4.jar%2394!/:?]
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:57) ~[toml-3.6.4.jar%2394!/:?]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.4.jar%2394!/:?]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.4.jar%2394!/:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.4.jar%2393!/:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.4.jar%2393!/:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.4.jar%2393!/:?]
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.4.jar%2393!/:?]
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.4.jar%2393!/:?]
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:43) ~[fmlcore-1.20.1-47.2.20.jar%23711!/:?]
	... 10 more
[14:58:08] [Server thread/INFO]: Mixing MixinGuiBook from enigmaticlegacy.mixins.json into vazkii.patchouli.client.book.gui.GuiBook
[14:58:08] [Server thread/INFO]: Renaming synthetic method lambda$onOpenWebLink$0(Ljava/lang/String;Lnet/minecraft/client/Minecraft;Lnet/minecraft/client/gui/screens/Screen;Z)V to md607d61$lambda$onOpenWebLink$0$0 in enigmaticlegacy.mixins.json:MixinGuiBook from mod (unknown)
[14:58:08] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Antonio Fuenzalida\curseforge\minecraft\Instances\Melee V Magicka Boss Rush\crash-reports\crash-2024-03-16_14.58.08-server.txt
[14:58:08] [Server thread/INFO]: Stopping server
[14:58:08] [Server thread/INFO]: Saving players
[14:58:08] [Server thread/INFO]: Saving worlds
[14:58:08] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.m_6857_()" because "serverlevel2" is null
	at net.minecraft.server.MinecraftServer.m_129885_(MinecraftServer.java:513) ~[client-1.20.1-20230612.114412-srg.jar%23710!/:?]
	at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:584) ~[client-1.20.1-20230612.114412-srg.jar%23710!/:?]
	at net.minecraft.client.server.IntegratedServer.m_7041_(IntegratedServer.java:187) ~[client-1.20.1-20230612.114412-srg.jar%23710!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23710!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23710!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:58:08] [Server thread/INFO]: Unloading server configs...`
My mods list is quite long (275 mods) and the pack I'm making is not yet released. I'm not sure if theres any place where all my mods are listed out but if absolutely necessary I can manually type down each one's name.

**Comment by cubicoder** [comment]
Ok I think I see the issue now, I'm guessing you're editing the config file directly? If you are, you need to put backslashes in front of the quotes around the fluid names and biome tags, like so: `dataList = ["{MinTicks:50,MaxTicks:60,Fluid:{FluidName:\"minecraft:lava\",Amount:1000},BiomeTags:[\"minecraft:is_nether\"]}", "{MinTicks:50,MaxTicks:60,Fluid:{FluidName:\"enlightened_end:ooze_fluid\",Amount:1000},BiomeTags:[\"minecraft:is_end\"]}"]`.

I usually use [Configured](https://www.curseforge.com/minecraft/mc-mods/configured) to edit the config in-game, so that's why I didn't catch this before--apparently Configured adds the backslashes for you. Hope that helps!

**Comment by 4AC11** [comment]
Thanks, it works now! I'll definitely be using configured from now on lol.
